'use client';

import { useState } from 'react';
import { FiArrowUpRight, FiMenu, FiX, FiPlay, FiCheck } from 'react-icons/fi';

const tracks = ['Machine Intelligence', 'Responsible AI', 'Computational Creativity'];

export default function Home() {
  const [open, setOpen] = useState(false);
  return <main>
    <nav className="fixed z-50 flex w-full items-center justify-between px-6 py-5 mix-blend-difference text-white md:px-12">
      <a href="#top" className="flex items-center gap-3 text-sm font-bold tracking-[.2em]"><span className="grid h-7 w-7 place-items-center rounded-full bg-white text-[11px] text-[#2864ff]">N</span>NOVA AI</a>
      <div className="hidden items-center gap-8 text-xs font-bold uppercase tracking-widest md:flex"><a href="#programme">Programme</a><a href="#research">Research</a><a href="#admissions">Admissions</a></div>
      <button aria-label="Toggle menu" onClick={() => setOpen(!open)} className="md:hidden">{open ? <FiX size={22}/> : <FiMenu size={22}/>}</button>
      <a href="#admissions" className="hidden rounded-full bg-white px-5 py-3 text-xs font-bold text-[#07111f] md:block">Apply now <FiArrowUpRight className="ml-2 inline"/></a>
    </nav>
    {open && <div className="fixed inset-0 z-40 flex flex-col justify-center gap-8 bg-[#07111f] px-8 text-3xl font-bold text-white md:hidden"><a href="#programme" onClick={() => setOpen(false)}>Programme</a><a href="#research" onClick={() => setOpen(false)}>Research</a><a href="#admissions" onClick={() => setOpen(false)}>Admissions</a></div>}

    <section id="top" className="grid-bg relative min-h-screen overflow-hidden bg-[#07111f] px-6 pb-16 pt-36 text-white md:px-12 md:pt-48">
      <div className="absolute right-[-10%] top-[15%] h-[560px] w-[560px] rounded-full bg-[#2864ff] opacity-30 blur-[120px]" />
      <div className="relative z-10 max-w-6xl"><p className="mb-8 flex items-center gap-3 text-xs font-bold uppercase tracking-[.28em] text-[#8db0ff]"><span className="h-px w-8 bg-[#8db0ff]"/> The future is a discipline</p><h1 className="display max-w-5xl text-[clamp(4.5rem,12vw,11rem)] font-bold">Build what<br/><span className="text-[#8db0ff]">thinks next.</span></h1><div className="mt-16 flex max-w-2xl flex-col justify-between gap-8 md:flex-row md:items-end"><p className="text-lg leading-relaxed text-slate-300">NOVA AI is an intensive master’s programme for curious minds building intelligent systems that move humanity forward.</p><a href="#programme" className="group flex shrink-0 items-center gap-4 text-sm font-bold uppercase tracking-widest">Explore the programme <span className="grid h-12 w-12 place-items-center rounded-full bg-[#2864ff] transition group-hover:scale-110"><FiArrowUpRight size={20}/></span></a></div></div>
      <div className="absolute bottom-8 right-8 hidden text-right text-xs uppercase tracking-widest text-slate-500 md:block">01 / 04<br/><span className="text-white">Intelligence, reimagined</span></div>
    </section>

    <section id="programme" className="px-6 py-24 md:px-12 md:py-36"><div className="mx-auto max-w-6xl"><div className="grid gap-12 md:grid-cols-[1fr_2fr]"><div><p className="text-xs font-bold uppercase tracking-[.25em] text-[#2864ff]">01 — The programme</p><h2 className="display mt-8 text-6xl font-bold md:text-8xl">Go deeper.<br/>Think wider.</h2></div><div className="pt-2"><p className="max-w-xl text-2xl leading-snug text-slate-600">One year. Three lenses. A lifetime of leverage. Learn to turn frontier research into useful, ethical, beautiful products.</p><div className="mt-16 divide-y divide-slate-200 border-y border-slate-200">{tracks.map((track, i) => <div key={track} className="flex items-center justify-between py-6"><span className="text-lg font-bold"><small className="mr-6 text-xs text-[#2864ff]">0{i + 1}</small>{track}</span><FiArrowUpRight className="text-slate-400"/></div>)}</div></div></div></div></section>

    <section id="research" className="bg-[#e7edff] px-6 py-24 md:px-12 md:py-36"><div className="mx-auto max-w-6xl"><div className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[.25em] text-[#2864ff]">02 — The studio</p><h2 className="display mt-8 text-6xl font-bold md:text-8xl">Make the<br/>impossible<br/><span className="text-[#2864ff]">useful.</span></h2></div><div className="max-w-xs text-sm leading-relaxed text-slate-600">Work in small, elite teams on live problems sourced from our research partners. Your capstone ships into the real world.</div></div><div className="mt-16 grid gap-4 md:grid-cols-3"><div className="glow relative h-72 overflow-hidden rounded-2xl bg-[#07111f] p-6 text-white md:col-span-2"><div className="absolute right-8 top-8 h-40 w-40 rounded-full border border-[#8db0ff]/40 bg-[#2864ff]/30 blur-sm"/><p className="relative text-xs uppercase tracking-widest text-[#8db0ff]">Studio 01</p><h3 className="absolute bottom-6 text-3xl font-bold">Synthetic worlds</h3></div><div className="flex h-72 flex-col justify-between rounded-2xl bg-white p-6"><FiPlay className="text-[#2864ff]" size={28}/><h3 className="text-3xl font-bold">Watch the<br/>NOVA method.</h3></div></div></div></section>

    <section id="admissions" className="bg-[#2864ff] px-6 py-24 text-white md:px-12 md:py-36"><div className="mx-auto max-w-6xl"><p className="text-xs font-bold uppercase tracking-[.25em] text-blue-200">03 — Admissions 2026</p><div className="mt-10 grid gap-12 md:grid-cols-2"><h2 className="display text-6xl font-bold md:text-8xl">Your next<br/>chapter<br/><span className="text-[#07111f]">starts here.</span></h2><div className="flex flex-col justify-end"><p className="mb-8 max-w-sm text-lg leading-relaxed text-blue-100">We look for restless thinkers, generous collaborators, and people who see possibility where others see complexity.</p><div className="space-y-4 border-t border-blue-300/50 pt-6 text-sm">{['Applications open 01 October 2025', 'Cohort begins September 2026', 'Based in London · Connected everywhere'].map(item => <p key={item}><FiCheck className="mr-3 inline"/>{item}</p>)}</div><a href="mailto:hello@nova.ai" className="mt-10 flex w-fit items-center rounded-full bg-[#07111f] px-6 py-4 text-sm font-bold">Start your application <FiArrowUpRight className="ml-4"/></a></div></div></div></section>
    <footer className="flex flex-col justify-between gap-8 bg-[#07111f] px-6 py-10 text-white md:flex-row md:items-center md:px-12"><div className="text-sm font-bold tracking-[.2em]">NOVA AI <span className="ml-3 font-normal tracking-normal text-slate-500">Master the intelligence age.</span></div><div className="text-xs text-slate-500">© 2026 NOVA AI Institute · Built for what’s next.</div></footer>
  </main>;
}
